### ISSUE TITLE
feat: bluetooth widget

### ISSUE THREAD

**Issue by C0m0n** [Snxwman/rancid#4]
- [ ] Device Status
  - [x] Paired
  - [x] Connected
  - [ ] Available
- [ ] Device connection
  - [x] Connect
  - [x] Disconnect
  - [ ] Autoconnect
- [ ] Device Pairing
  - [ ] Pair device
  - [ ] Forget device
- [x] Per device battery status
- [x] System bluetooth toggle

**Comment by Snxwman** [comment]
Remaining functions needs a lot more work on the script side.
